### PR TITLE
Fix: Status "In progress — Title contains" when a label is matched

### LINKED ISSUE #173: Status "In progress — Title contains" when a label is matched
When labels are configured in the `wip.yml` file, and one label is matched, the status text shows `In progress — Title contains XXX`, I'd expect something like `In progress — Label contains XXX` instead

### PR DESCRIPTION
**Pull request by HaydenMeloche**
This PR fixes the bug found where when a match is found in a label, the status would be:
`Title contains {match}` rather than `Label contains {match}`.

Purposed Changes: 
	- Updated existing test to include check for title
	- Update the title to include the location of where the match was found

closes #173

### CODE REVIEW

File: lib/pro/set-status.js [hunk 1]
```diff
@@ -22,14 +22,20 @@ function setStatusPro (newStatus, context) {
     output = `a ${output.name} emoji` // Emoji match
   }
 
+  let location = locationLabel[newStatus.location]
+
+  if (location !== undefined) {
+    location = location.charAt(0).toUpperCase() + location.slice(1) // Make first letter of word capitalize
+  }
```
Comment (gr2m) [inline lib/pro/set-status.js]: nice 👍

File: test/integration/pro-plan-test.js [hunk 2]
```diff
@@ -345,6 +345,7 @@ test('custom location: label_name', async function (t) {
   const logParams = this.logMock.child.lastCall.arg
   t.is(logParams.location, 'label_name')
   t.is(logParams.match, 'WIP')
+  t.is(createCheckParams.output.title, 'Label contains "WIP"')
```
Comment (gr2m) [inline test/integration/pro-plan-test.js]: 👍
